[package]
name = "runway-rbx"
description = "Asset manager for Roblox projects"
version = "0.2.0"
edition = "2021"
license = "MIT"

readme = "README.md"
repository = "https://github.com/fractalbeauty/runway"
homepage = "https://github.com/fractalbeauty/runway"

[[bin]]
name = "runway"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.71"
arl = "0.1.0"
async-trait = "0.1.71"
blake3 = "1.4.1"
clap = { version = "4.3.11", features = ["derive", "env"] }
clap-verbosity-flag = "2.0.1"
debug-ignore = "1.0.5"
futures = "0.3.28"
ignore = "0.4.20"
log = "0.4.19"
notify = "6.0.1"
once_cell = "1.18.0"
png = "0.17.10"
pretty_env_logger = "0.5.0"
rbxcloud = "0.5.0"
regex = "1.9.1"
reqwest = "0.11.18"
secrecy = "0.8.0"
serde = { version = "1.0.171", features = ["derive", "rc"] }
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["macros", "rt", "fs", "sync", "signal", "time"] }
toml = "0.7.6"
unicode-ident = "1.0.10"

[target.'cfg(windows)'.dependencies]
junction = "1.0.0"
known-folders = "1.0.1"
